version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5441:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/14/data
    restart: unless-stopped
  
  pet:
    container_name: lapka_pet
    build: .
    image: lapka_pet_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5040:5040
      - 5041:5041
    depends_on:
      - postgres
    restart: unless-stopped