version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5441:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/14/data
    restart: unless-stopped
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lapka_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  
